-- GENERATED by External/keku/make_accessory_bones.py from Rime's mesh_roundtrip -- do not edit by hand.
--
-- The skeleton bones (1-based into weaponStates[1].mesh3pTransforms, WeaponSke01's order) each accessory mesh's
-- skin is weighted to. A skinned socket object spawns at the origin and its skin puts it on these, so this is
-- what says where the piece actually is -- the view frames it there. Rigid meshes are not listed: they carry
-- their own transform.
return {
	["weapons/accessories/bipod/bipod_1p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/accessories/bipod/bipod_3p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/accessories/foregrip/foregrip_1p_mesh"] = { 2, 18 },   -- Wep_Root, Wep_Bipod1
	["weapons/accessories/foregrip/foregrip_3p_mesh"] = { 2, 18 },   -- Wep_Root, Wep_Bipod1
	["weapons/kh2002/kh2002_frontgrip_1p_mesh"] = { 18 },   -- Wep_Bipod1
	["weapons/kh2002/kh2002_frontgrip_3p_mesh"] = { 18 },   -- Wep_Bipod1
	["weapons/m240/m240_bipods_1p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/m240/m240_bipods_3p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/m249/m249_bipods_1p_mesh"] = { 2, 18, 19, 20 },   -- Wep_Root, Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/m249/m249_bipods_3p_mesh"] = { 2, 18, 19, 20 },   -- Wep_Root, Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/m60/m60_bipods_1p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/m60/m60_bipods_3p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/magpulpdr/magpulpdr_extendedmag_1p_mesh"] = { 8 },   -- Wep_Mag
	["weapons/magpulpdr/magpulpdr_extendedmag_3p_mesh"] = { 8 },   -- Wep_Mag
	["weapons/magpulpdr/magpulpdr_regularmag_1p_mesh"] = { 8 },   -- Wep_Mag
	["weapons/magpulpdr/magpulpdr_regularmag_3p_mesh"] = { 8 },   -- Wep_Mag
	["weapons/mp7/mp7_extendedmag_1p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/mp7/mp7_extendedmag_3p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/mp7/mp7_regularmag_1p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/mp7/mp7_regularmag_3p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/pecheneg/pecheneg_bipods_1p_mesh"] = { 19, 20 },   -- Wep_Bipod2, Wep_Bipod3
	["weapons/pecheneg/pecheneg_bipods_3p_mesh"] = { 19, 20 },   -- Wep_Bipod2, Wep_Bipod3
	["weapons/pp2000/pp2000_mag_1p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/pp2000/pp2000_mag_3p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/pp2000/pp2000_mag_extended_1p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/pp2000/pp2000_mag_extended_3p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/saiga20k/saiga_20k_extendedmag_1p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/saiga20k/saiga_20k_extendedmag_3p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/saiga20k/saiga_20k_regularmag_1p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/saiga20k/saiga_20k_regularmag_3p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/sv98/sv98_bipods_1p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/sv98/sv98_bipods_3p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/type88/type_88_bipod_1p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/type88/type_88_bipod_3p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/usas-12/usas_12_extendedmag_1p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/usas-12/usas_12_extendedmag_3p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/usas-12/usas_12_regularmag_1p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/usas-12/usas_12_regularmag_3p_mesh"] = { 8, 9 },   -- Wep_Mag, Wep_Mag_Ammo
	["weapons/xp1_famas/xp1_famas_bipod_1p_mesh"] = { 19, 20 },   -- Wep_Bipod2, Wep_Bipod3
	["weapons/xp1_famas/xp1_famas_bipod_3p_mesh"] = { 19, 20 },   -- Wep_Bipod2, Wep_Bipod3
	["weapons/xp1_qbb-95/qbb-95_bipod2_1p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/xp1_qbb-95/qbb-95_bipod2_3p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/xp1_qbu-88/qbu-88_bipod2_1p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/xp1_qbu-88/qbu-88_bipod2_3p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/xp2_l86/l86_bipods_1p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/xp2_l86/l86_bipods_3p_mesh"] = { 18, 19, 20 },   -- Wep_Bipod1, Wep_Bipod2, Wep_Bipod3
	["weapons/xp2_mp5k/mp5k_extendedmag_1p_mesh"] = { 8 },   -- Wep_Mag
	["weapons/xp2_mp5k/mp5k_extendedmag_3p_mesh"] = { 8 },   -- Wep_Mag
	["weapons/xp2_mp5k/mp5k_regularmag_1p_mesh"] = { 8 },   -- Wep_Mag
	["weapons/xp2_mp5k/mp5k_regularmag_3p_mesh"] = { 8 },   -- Wep_Mag
}
