-- The pistols as the weapon view draws them (3P mesh posed with its EBX deltas), per mesh leaf (lower case, which a camo's
-- clone of the mesh shares): the centre and radius of the drawn weapon -- its authored box is the BIND pose's, so it cannot
-- say -- and the bones whose piece those deltas park outside the weapon (mesh3pTransforms index), which the game never shows.
-- Generated by External/keku/sidearm_pieces.py from Rime's dump_mesh_sections; do not edit by hand.
return {
  ["taurus44_3p_mesh"] = { centre = { 0.0001, -0.0300, 0.1135 }, radius = 0.1475, hide = { 9 } },   -- hides Wep_Mag_Ammo; drawn box (-0.022,-0.104,-0.034)..(+0.023,+0.044,+0.261)
  ["taurus44_gm_3p_mesh"] = { centre = { 0.0001, -0.0300, 0.1135 }, radius = 0.1475, hide = { 9 } },   -- the Gun Master copy of taurus44_3p_mesh
  ["m93r_3p_mesh"] = { centre = { 0.0007, -0.0225, 0.1270 }, radius = 0.1391, hide = {  } },   -- hides none; drawn box (-0.019,-0.118,-0.012)..(+0.020,+0.073,+0.266)
  ["m93r_gm_3p_mesh"] = { centre = { 0.0007, -0.0225, 0.1270 }, radius = 0.1391, hide = {  } },   -- the Gun Master copy of m93r_3p_mesh
  ["m9_3p_mesh"] = { centre = { 0.0007, -0.0076, 0.1152 }, radius = 0.1273, hide = {  } },   -- hides none; drawn box (-0.019,-0.086,-0.012)..(+0.020,+0.071,+0.242)
  ["m9_gm_3p_mesh"] = { centre = { 0.0007, -0.0076, 0.1152 }, radius = 0.1273, hide = {  } },   -- the Gun Master copy of m9_3p_mesh
  ["glock18_3p_mesh"] = { centre = { 0.0003, -0.0177, 0.0894 }, radius = 0.1105, hide = {  } },   -- hides none; drawn box (-0.017,-0.093,-0.021)..(+0.017,+0.058,+0.200)
  ["m1911_3p_mesh"] = { centre = { 0.0005, -0.0123, 0.1097 }, radius = 0.1187, hide = {  } },   -- hides none; drawn box (-0.015,-0.091,-0.009)..(+0.016,+0.067,+0.228)
  ["mp412rex_3p_mesh"] = { centre = { 0.0000, -0.0064, 0.1090 }, radius = 0.1206, hide = {  } },   -- hides none; drawn box (-0.017,-0.083,-0.012)..(+0.017,+0.070,+0.230)
  ["mp443_3p_mesh"] = { centre = { 0.0000, -0.0082, 0.1002 }, radius = 0.1075, hide = {  } },   -- hides none; drawn box (-0.017,-0.085,-0.007)..(+0.017,+0.069,+0.208)
  ["mp443_gm_3p_mesh"] = { centre = { 0.0000, -0.0082, 0.1002 }, radius = 0.1075, hide = {  } },   -- the Gun Master copy of mp443_3p_mesh
  ["xp4_crossbow_prototype_3p_mesh"] = { centre = { -0.0000, -0.0161, 0.4660 }, radius = 0.4949, hide = { 10, 11, 12, 23 } },   -- hides Wep_Physic1, Wep_Physic2, Wep_Physic3, Wep_Extra2; drawn box (-0.345,-0.122,-0.029)..(+0.345,+0.090,+0.961)
}
