namespace RimeLib.Cmd.UiBuilder
{
    /// <summary>
    /// The VeniceEXT side of a generated UI mod. Two files: ext/Shared ships the superbundle at the two
    /// injection points a UI resource needs, ext/Client edits the live screen graphs. Both are the code that
    /// was verified in game on 2026-09-15 (CustomizeCamoGrid), with the per-screen data moved into a table
    /// the emitter fills in. Placeholders: {{MOD}}, {{SUPERBUNDLE}}, {{BUNDLE}}, {{SCREENS}}.
    /// </summary>
    public static class LuaTemplates
    {
        public const string Shared = @"-- {{MOD}} -- generated by Rime ui_build_mod. Edit the screen document and rebuild; do not edit this file.
--
-- Ships the mod's superbundle. A UI resource has to be mounted BEFORE the pass that binds it:
--   . the level's MAIN pass binds widget movies (ui/assets/<widget>)          -> PREPEND there
--   . the <level>_UiPlaying pass is where screen movies resolve (at push time) -> APPEND there
-- Guard of three conditions: superbundle mounted this level + '_uiplaying' + the CURRENT level name, because
-- the frontend has a _UiPlaying pass of its own and injecting there hangs the client on a black screen.
-- Shared on purpose: the server never matches these passes.

local SUPERBUNDLE = ""{{SUPERBUNDLE}}""
local BUNDLE = ""{{BUNDLE}}""
-- the mod's pictures: their texture headers ride in the bundle, their pixels in this chunk store (empty = no pictures)
local CHUNKS = ""{{CHUNKS}}""

local m_Mounted = false

local function LOG(p_Text)
	print(""[{{MOD}}/sb] "" .. tostring(p_Text))
end

Events:Subscribe(""Level:LoadResources"", function()
	m_Mounted = pcall(function() ResourceManager:MountSuperBundle(SUPERBUNDLE) end)
	LOG(""level starting -- superbundle mounted: "" .. tostring(m_Mounted))
	if CHUNKS ~= """" then
		local s_Chunks = pcall(function() ResourceManager:MountSuperBundle(CHUNKS) end)
		LOG(""picture chunk store mounted: "" .. tostring(s_Chunks))
	end
end)

Hooks:Install(""ResourceManager:LoadBundles"", 100, function(p_Hook, p_Bundles, p_Compartment)
	local s_Names = {}
	for _, l_Name in ipairs(p_Bundles) do
		s_Names[#s_Names + 1] = tostring(l_Name)
	end

	local s_Level = """"
	pcall(function() s_Level = string.lower(tostring(SharedUtils:GetLevelName() or """")) end)

	if not m_Mounted or s_Level == """" or string.find(s_Level, ""frontend"", 1, true) ~= nil then
		return
	end

	local s_IsMain = false
	local s_IsUiPlaying = false
	for _, l_Name in ipairs(s_Names) do
		local l_Lower = string.lower(l_Name)
		if l_Lower == s_Level then
			s_IsMain = true
		end
		if string.find(l_Lower, ""_uiplaying"", 1, true) ~= nil and string.find(l_Lower, s_Level, 1, true) ~= nil then
			s_IsUiPlaying = true
		end
		if l_Name == BUNDLE then
			return -- already ours; never inject twice into the same call
		end
	end

	if s_IsMain then
		local s_First = { BUNDLE }
		for _, l_Name in ipairs(p_Bundles) do
			s_First[#s_First + 1] = l_Name
		end
		LOG(""prepending our bundle to the MAIN level pass"")
		p_Hook:Pass(s_First, p_Compartment)
		return
	end

	if s_IsUiPlaying then
		local s_New = {}
		for _, l_Name in ipairs(p_Bundles) do
			s_New[#s_New + 1] = l_Name
		end
		s_New[#s_New + 1] = BUNDLE
		LOG(""appending our bundle to the UiPlaying pass"")
		p_Hook:Pass(s_New, p_Compartment)
	end
end)
";

        public const string Client = @"-- {{MOD}} -- generated by Rime ui_build_mod. Edit the screen document and rebuild; do not edit this file.
--
-- Edits live UI screen graphs from VeniceEXT, without shipping any EBX (a screen partition in a bundle hangs
-- the client; editing the loaded asset does not). Mechanisms, each verified in game on 2026-09-15:
--   . RegisterInstanceLoadHandler on the UIScreenAsset fires before the screen is instantiated
--   . a WidgetNode (and its binding, ports, connections) CREATED in Lua must be born with a GUID, or the
--     engine dies instantiating the graph -- every created instance here has one, baked in at build time
--   . created instances are kept referenced for the mod's lifetime
--   . the stage clip named like the node's InstanceName must exist in the screen's movie (ext/Shared ships it)

{{SCREENS}}

local m_Keep = {}
local m_Loaded = {}
local m_Graph = nil   -- the graph being edited (a port reference resolves against it)

-- ⛔⛔ THE GRAPH EDITOR'S REPORT HAS TO REACH DISK, NOT ONLY THE CONSOLE (2026-09-21, after it cost two boots of
-- keku's: a door rewired through a node of ours stopped opening its screen, and the one thing that would have said
-- why -- whether the node was created and the wire applied -- was printed where nobody can read it afterwards. The
-- console has a short scrollback and he cannot copy it; every diagnostic of ours goes to the mod's database).
-- ⚠ NOT EVERY LINE: this runs once per level but prints one line per node and per wire of every screen, and a few
-- hundred net events at level load is exactly the instrumenting cost that has made his client lag before. So what
-- travels is what a reader needs: anything that FAILED or was skipped, and the per-screen summary. The rule lives
-- HERE, in one place -- a filter repeated at each call site is a filter that forgets a line the day it matters.
local function GRAPH_TRAVELS(p_Text)
	return string.find(p_Text, ""false"", 1, true) ~= nil or string.find(p_Text, ""NOT found"", 1, true) ~= nil or
		string.find(p_Text, ""SKIPPED"", 1, true) ~= nil or string.find(p_Text, ""skipping"", 1, true) ~= nil or
		string.find(p_Text, ""[SCREEN]"", 1, true) ~= nil or string.find(p_Text, ""[WIRE]"", 1, true) ~= nil or
		string.find(p_Text, ""[ADD]"", 1, true) ~= nil or string.find(p_Text, ""[NODE] new"", 1, true) ~= nil or
		string.find(p_Text, ""[UNWIRE]"", 1, true) ~= nil or string.find(p_Text, ""=== done"", 1, true) ~= nil or
		string.find(p_Text, ""; ours: "", 1, true) ~= nil
end

local function LOG(p_Text)
	local s_Text = tostring(p_Text)
	print(""[{{MOD}}] "" .. s_Text)

	if GRAPH_TRAVELS(s_Text) then
		-- the camo framework's server side files these; the same road the weapon view's readings take
		pcall(function() NetEvents:Send(""WeaponCamo:Log"", ""[graph] "" .. s_Text) end)
	end
end

-- Casts a DataContainer to its runtime type (the constructor of that type is a global).
local function CastAny(p_Instance)
	local s_Result = nil
	pcall(function() s_Result = _G[p_Instance.typeInfo.name](p_Instance) end)
	return s_Result
end

local function NodeLabel(p_Node)
	local s_Label = nil
	pcall(function() s_Label = p_Node.instanceName end)
	if s_Label == nil or tostring(s_Label) == """" then
		pcall(function() s_Label = p_Node.name end)
	end
	return tostring(s_Label)
end

local function FindNode(p_Screen, p_Label)
	for i = 1, #p_Screen.nodes do
		local l_Node = CastAny(p_Screen.nodes[i])
		if l_Node ~= nil and NodeLabel(l_Node) == p_Label then
			return l_Node
		end
	end
	return nil
end

local function InputPortByEvent(p_Node, p_Event)
	local s_Query = UIWidgetEventID[""UIWidgetEventID_"" .. p_Event]
	for i = 1, #p_Node.inputs do
		if p_Node.inputs[i].query == s_Query then
			return p_Node.inputs[i]
		end
	end
	return nil
end

local ResolvePort   -- defined below; a port reference field needs it
local WriteInstanceFields

-- A field value described by the document: { kind = string|bool|number|enum|ref|struct|list|portref|instance, ... }.
local function BuildValue(p_Desc)
	if p_Desc.kind == ""instance"" then
		-- a DataContainer described inline (a data binding), born with its stable guid
		local s_Ctor = _G[p_Desc.type]
		if s_Ctor == nil then error(""no such type "" .. tostring(p_Desc.type)) end
		local s_Instance = s_Ctor(Guid(p_Desc.guid))
		m_Keep[#m_Keep + 1] = s_Instance
		WriteInstanceFields(s_Instance, p_Desc.fields)
		return s_Instance
	elseif p_Desc.kind == ""portref"" then
		-- another node's port on the same graph (JumpNode.TargetPort = ""Confirm.inValue"")
		local s_Target = m_Graph ~= nil and FindNode(m_Graph, p_Desc.node) or nil
		if s_Target == nil then error(""portref: node "" .. tostring(p_Desc.node) .. "" not found"") end
		local s_Port = ResolvePort(s_Target, p_Desc.port)
		if s_Port == nil then error(""portref: port "" .. tostring(p_Desc.port) .. "" not found on "" .. tostring(p_Desc.node)) end
		return s_Port
	elseif p_Desc.kind == ""enum"" then
		local s_Enum = _G[p_Desc.enum]
		return s_Enum ~= nil and s_Enum[p_Desc.value] or nil
	elseif p_Desc.kind == ""ref"" then
		-- the loaded instance, cast to the field's type when that type exists (a DataContainer does not go into a typed ref as-is)
		local s_Value = m_Loaded[p_Desc.asset]
		if s_Value ~= nil and p_Desc.type ~= nil and _G[p_Desc.type] ~= nil then
			local l_Ok, l_Cast = pcall(function() return _G[p_Desc.type](s_Value) end)
			if l_Ok and l_Cast ~= nil then s_Value = l_Cast end
		end
		return s_Value
	elseif p_Desc.kind == ""struct"" then
		local s_Ctor = _G[p_Desc.type]
		if s_Ctor == nil then return nil end
		local s_Value = s_Ctor()
		for _, l_Field in ipairs(p_Desc.fields) do
			local l_Ok, l_Err = pcall(function() s_Value[l_Field.name] = BuildValue(l_Field) end)
			if not l_Ok then LOG(""      struct "" .. p_Desc.type .. ""."" .. l_Field.name .. "": "" .. tostring(l_Err)) end
		end
		return s_Value
	else
		return p_Desc.value
	end
end

-- Vectors: '#' and '[i]' are 1-based, ':erase(i)' takes a 0-based index (measured in game on selectableUnlocks); ':clear()' empties.
local function ClearArray(p_Array)
	local s_Ok = pcall(function() p_Array:clear() end)
	if not s_Ok then
		for i = #p_Array - 1, 0, -1 do
			p_Array:erase(i)
		end
	end
end

-- The fields of an instance described inline: the document holds the WHOLE instance, so a list is replaced, not appended to.
WriteInstanceFields = function(p_Instance, p_Fields)
	for _, l_Field in ipairs(p_Fields or {}) do
		local l_Ok, l_Err
		if l_Field.kind == ""list"" then
			l_Ok, l_Err = pcall(function()
				ClearArray(p_Instance[l_Field.name])
				for _, l_Item in ipairs(l_Field.items) do
					p_Instance[l_Field.name]:add(BuildValue(l_Item))
				end
			end)
		else
			l_Ok, l_Err = pcall(function() p_Instance[l_Field.name] = BuildValue(l_Field) end)
		end
		if not l_Ok then LOG(""      instance field "" .. tostring(l_Field.name) .. "" FAILED: "" .. tostring(l_Err)) end
	end
end

-- An inline instance on a node: edited in place when the node already carries one of that type (MakeWritable),
-- else created and assigned.
local function WriteInstance(p_Node, p_Field)
	local s_Current, s_Same = nil, false
	pcall(function() s_Current = p_Node[p_Field.name] end)
	if s_Current ~= nil then
		pcall(function() s_Same = s_Current.typeInfo.name == p_Field.type end)
	end
	if s_Same then
		local s_Target = _G[p_Field.type](s_Current)
		pcall(function() s_Target:MakeWritable() end)
		WriteInstanceFields(s_Target, p_Field.fields)
		LOG(""      instance "" .. p_Field.name .. "" ("" .. p_Field.type .. "") edited in place"")
	else
		p_Node[p_Field.name] = BuildValue(p_Field)
		LOG(""      instance "" .. p_Field.name .. "" ("" .. p_Field.type .. "") created"")
	end
end

-- Writes the typed fields of any node type; lists are appended element by element.
local function WriteFields(p_Node, p_Fields)
	local s_Ok, s_Failed = 0, 0
	for _, l_Field in ipairs(p_Fields or {}) do
		local l_Ok, l_Err
		if l_Field.kind == ""list"" then
			l_Ok, l_Err = pcall(function()
				for _, l_Item in ipairs(l_Field.items) do
					p_Node[l_Field.name]:add(BuildValue(l_Item))
				end
			end)
		elseif l_Field.kind == ""instance"" then
			l_Ok, l_Err = pcall(function() WriteInstance(p_Node, l_Field) end)
		else
			l_Ok, l_Err = pcall(function() p_Node[l_Field.name] = BuildValue(l_Field) end)
		end
		if l_Ok then s_Ok = s_Ok + 1 else s_Failed = s_Failed + 1; LOG(""      field "" .. tostring(l_Field.name) .. "" FAILED: "" .. tostring(l_Err)) end
	end
	if s_Ok + s_Failed > 0 then LOG(string.format(""    [FIELDS] %d written, %d failed"", s_Ok, s_Failed)) end
end

-- A plain UINodePort, or (p_InputEvent = a UIInputAction name) a UIInputEventNodePort: the port a StateNode's
-- Outputs use to react to a controller/keyboard action.
local function NewPort(p_Guid, p_Name, p_Event, p_InputEvent, p_InstanceName)
	local s_Port
	if p_InputEvent ~= nil then
		s_Port = UIInputEventNodePort(Guid(p_Guid))
		s_Port.inputEventType = UIInputAction[""UIInputAction_"" .. p_InputEvent]
	else
		s_Port = UINodePort(Guid(p_Guid))
	end
	s_Port.name = p_Name
	s_Port.instanceName = p_InstanceName or p_Name
	s_Port.query = p_Event ~= nil and UIWidgetEventID[""UIWidgetEventID_"" .. p_Event] or UIWidgetEventID.UIWidgetEventID_None
	s_Port.allowManualRemove = false
	m_Keep[#m_Keep + 1] = s_Port
	return s_Port
end

-- The ports a NEW non-widget node needs: one per single-port field (In, Out, True…) plus the named array ports asked for.
local function CreatePorts(p_Node, p_Entry)
	for _, l_Port in ipairs(p_Entry.singlePorts or {}) do
		local l_Ok, l_Err = pcall(function() p_Node[l_Port.field] = NewPort(l_Port.guid, l_Port.name, nil, nil) end)
		if not l_Ok then LOG(""      port "" .. l_Port.field .. "" FAILED: "" .. tostring(l_Err)) end
	end
	for _, l_Port in ipairs(p_Entry.ports or {}) do
		local l_Ok, l_Err = pcall(function() p_Node[l_Port.field]:add(NewPort(l_Port.guid, l_Port.name, l_Port.event, l_Port.inputEvent, l_Port.instanceName)) end)
		if not l_Ok then LOG(""      port "" .. l_Port.field .. "":"" .. l_Port.name .. "" FAILED: "" .. tostring(l_Err)) end
	end
end

-- ""out"" / ""inValue"" / ""show"" = a port field; ""outputs:NAME"" / ""inputs:NAME"" = the port of that name (or event) in the array.
ResolvePort = function(p_Node, p_Spec)
	local s_Colon = string.find(p_Spec, "":"", 1, true)
	if s_Colon == nil then
		local s_Port = nil
		pcall(function() s_Port = p_Node[p_Spec] end)
		return s_Port
	end
	local s_Field = string.sub(p_Spec, 1, s_Colon - 1)
	local s_Name = string.sub(p_Spec, s_Colon + 1)
	local s_Query = UIWidgetEventID[""UIWidgetEventID_"" .. s_Name]
	local s_Found = nil
	pcall(function()
		local l_Array = p_Node[s_Field]
		for i = 1, #l_Array do
			local l_Port = l_Array[i]
			if l_Port.name == s_Name or l_Port.instanceName == s_Name or (s_Query ~= nil and l_Port.query == s_Query and s_Query ~= UIWidgetEventID.UIWidgetEventID_None) then
				s_Found = l_Port
				break
			end
		end
	end)
	return s_Found
end

local function WriteProperties(p_Node, p_Entry)
	local s_Existing = #p_Node.widgetProperties
	local s_Reused, s_Added, s_Failed = 0, 0, 0
	for i, l_Pair in ipairs(p_Entry.properties) do
		local l_Ok
		if i <= s_Existing then
			l_Ok = pcall(function()
				p_Node.widgetProperties[i].name = l_Pair[1]
				p_Node.widgetProperties[i].value = l_Pair[2]
			end)
			if l_Ok then s_Reused = s_Reused + 1 end
		else
			l_Ok = pcall(function()
				local l_Property = UIWidgetProperty()
				l_Property.name = l_Pair[1]
				l_Property.value = l_Pair[2]
				p_Node.widgetProperties:add(l_Property)
			end)
			if l_Ok then s_Added = s_Added + 1 end
		end
		if not l_Ok then s_Failed = s_Failed + 1 end
	end
	local s_Removed = 0
	if p_Entry.replaceProperties then
		-- ':erase' takes a 0-based index: drop the entries past the document's count, from the end
		pcall(function()
			for i = #p_Node.widgetProperties - 1, #p_Entry.properties, -1 do
				p_Node.widgetProperties:erase(i)
				s_Removed = s_Removed + 1
			end
		end)
	end
	LOG(string.format(""    [PROPS] %s: %d rewritten, %d appended, %d removed, %d failed"", p_Entry.instanceName, s_Reused, s_Added, s_Removed, s_Failed))
end

local function CategoryFrom(p_Screen, p_Label)
	local s_Node = FindNode(p_Screen, p_Label)
	local s_Category = nil
	pcall(function() s_Category = UIDynamicDataBinding(s_Node.dataBinding).bindings[1].dataCategory end)
	return s_Category
end

local function WriteBinding(p_Screen, p_Node, p_Entry)
	local b = p_Entry.binding
	if b == nil then
		return
	end
	local s_Category = b.categoryFromNode ~= nil and CategoryFrom(p_Screen, b.categoryFromNode) or nil
	if s_Category == nil and b.category ~= nil then
		s_Category = m_Loaded[b.category]
	end
	if p_Entry.new then
		local s_Ok, s_Err = pcall(function()
			local l_Binding = UIDynamicDataBinding(Guid(p_Entry.bindingGuid))
			l_Binding.refresh = true
			local l_Source = UIDataSourceInfo()
			l_Source.dataName = b.dataName
			l_Source.dataKey = b.dataKey
			l_Source.dataCategory = s_Category
			l_Source.useDirectAccess = b.useDirectAccess
			l_Source.updateOnInitialize = b.updateOnInitialize
			l_Binding.bindings:add(l_Source)
			p_Node.dataBinding = l_Binding
			m_Keep[#m_Keep + 1] = l_Binding
			m_Keep[#m_Keep + 1] = s_Category
		end)
		LOG(""    [BIND] "" .. p_Entry.instanceName .. "" new binding "" .. b.dataName .. "" / "" .. tostring(b.dataKey) .. "" -> "" .. tostring(s_Ok) .. (s_Ok and """" or (""  "" .. tostring(s_Err))))
	else
		local s_Ok, s_Err = pcall(function()
			local l_Binding = UIDynamicDataBinding(p_Node.dataBinding)
			l_Binding:MakeWritable()
			l_Binding.bindings[1].dataName = b.dataName
			l_Binding.bindings[1].dataKey = b.dataKey
			if s_Category ~= nil then
				l_Binding.bindings[1].dataCategory = s_Category
			end
			l_Binding.bindings[1].useDirectAccess = b.useDirectAccess
			l_Binding.bindings[1].updateOnInitialize = b.updateOnInitialize
		end)
		LOG(""    [BIND] "" .. p_Entry.instanceName .. "" rewired to "" .. b.dataName .. "" / "" .. tostring(b.dataKey) .. "" -> "" .. tostring(s_Ok) .. (s_Ok and """" or (""  "" .. tostring(s_Err))))
	end
end

local function Wire(p_Screen, p_Node, p_Entry)
	for _, c in ipairs(p_Entry.connections) do
		local s_From = c.event or c.fromPort or ""out""
		local s_To = c.toEvent or c.toPort or ""inValue""
		local s_Target = FindNode(p_Screen, c.toNode)
		local s_TargetPort = nil
		if s_Target ~= nil then
			if c.toEvent ~= nil then
				s_TargetPort = InputPortByEvent(s_Target, c.toEvent)
				if s_TargetPort == nil and c.targetPortGuid ~= nil then
					-- the widget's contract has the event but no shipped wire hit it, so the node has no input port for it yet:
					-- create it the way the shipped ones are (a UINodePort in inputs, query = the event, named after the node)
					pcall(function() s_Target:MakeWritable() end)
					local l_Ok, l_Err = pcall(function()
						local l_In = NewPort(c.targetPortGuid, NodeLabel(s_Target), c.toEvent)
						s_Target.inputs:add(l_In)
						s_TargetPort = l_In
					end)
					LOG(string.format(""    [PORT] %s new input port %s -> %s%s"", c.toNode, c.toEvent, tostring(l_Ok), l_Ok and """" or (""  "" .. tostring(l_Err))))
				end
			else
				s_TargetPort = ResolvePort(s_Target, c.toPort or ""inValue"")
			end
		end
		if s_Target == nil or s_TargetPort == nil then
			LOG(string.format(""    [WIRE] %s.%s -> %s.%s: target %s -- SKIPPED"", p_Entry.instanceName, s_From, c.toNode, s_To, s_Target == nil and ""node not found"" or ""port not found""))
		else
			local s_Ok, s_Err = pcall(function()
				local l_Port
				if c.event ~= nil then
					-- widget style: a new output port firing this event
					l_Port = NewPort(c.portGuid, p_Entry.instanceName, c.event)
					p_Node.outputs:add(l_Port)
				else
					l_Port = ResolvePort(p_Node, c.fromPort or ""out"")
					if l_Port == nil then
						-- an array port that does not exist yet (outputs:NAME): create it
						local l_Colon = string.find(c.fromPort or """", "":"", 1, true)
						if l_Colon ~= nil then
							l_Port = NewPort(c.portGuid, string.sub(c.fromPort, l_Colon + 1), nil)
							p_Node[string.sub(c.fromPort, 1, l_Colon - 1)]:add(l_Port)
						end
					end
				end
				if l_Port == nil then error(""source port "" .. s_From .. "" not found"") end
				local l_Conn = UINodeConnection(Guid(c.connGuid))
				l_Conn.sourceNode = p_Node
				l_Conn.sourcePort = l_Port
				l_Conn.targetNode = s_Target
				l_Conn.targetPort = s_TargetPort
				l_Conn.numScreensToPop = c.pop or 0
				p_Screen.connections:add(l_Conn)
				m_Keep[#m_Keep + 1] = l_Conn
			end)
			LOG(string.format(""    [WIRE] %s.%s -> %s.%s -> %s%s"", p_Entry.instanceName, s_From, c.toNode, s_To, tostring(s_Ok), s_Ok and """" or (""  "" .. tostring(s_Err))))
		end
	end
end

local function ApplyNode(p_ScreenData, p_Screen, p_Entry)
	local s_Widget = p_Entry.widget ~= nil and m_Loaded[p_Entry.widget] or nil
	if p_Entry.widget ~= nil and s_Widget == nil then
		LOG(""    widget asset "" .. p_Entry.widget .. "" not loaded -- skipping "" .. p_Entry.instanceName)
		return
	end
	local s_IsWidget = p_Entry.type == nil or p_Entry.type == ""WidgetNode""
	local s_Node
	if p_Entry.new and not s_IsWidget then
		-- any other node type: constructed by name (every DataContainer type is a global), born with a guid
		local s_Ok, s_Err = pcall(function()
			local l_Ctor = _G[p_Entry.type]
			if l_Ctor == nil then error(""no such type "" .. tostring(p_Entry.type)) end
			s_Node = l_Ctor(Guid(p_Entry.guid))
			s_Node.name = p_Entry.instanceName
			pcall(function() s_Node.instanceName = p_Entry.instanceName end)
			s_Node.parentGraph = p_Screen
			s_Node.isRootNode = false
			s_Node.parentIsScreen = p_ScreenData.isScreen ~= false
			m_Keep[#m_Keep + 1] = s_Node
		end)
		LOG(""  [NODE] new "" .. p_Entry.type .. "" "" .. p_Entry.instanceName .. "" -> "" .. tostring(s_Ok) .. (s_Ok and """" or (""  "" .. tostring(s_Err))))
		if not s_Ok then return end
		CreatePorts(s_Node, p_Entry)
	elseif p_Entry.new then
		local s_Ok, s_Err = pcall(function()
			s_Node = WidgetNode(Guid(p_Entry.guid))
			s_Node.name = p_Entry.instanceName
			s_Node.instanceName = p_Entry.instanceName
			s_Node.parentGraph = p_Screen
			s_Node.isRootNode = false
			s_Node.parentIsScreen = p_ScreenData.isScreen ~= false
			s_Node.widgetAsset = UIWidgetAsset(s_Widget)
			s_Node.focusIndex = p_Entry.focusIndex
			s_Node.zDepthLevel = p_Entry.zDepthLevel
			s_Node.alwaysInFocus = false
			s_Node.verticalAlign = WidgetVerticalAlignment.WVA_Center
			s_Node.horisontalAlign = WidgetHorisontalAlignment.WHA_Center
			m_Keep[#m_Keep + 1] = s_Node
		end)
		LOG(""  [NODE] new "" .. p_Entry.instanceName .. "" ("" .. tostring(p_Entry.widget) .. "") -> "" .. tostring(s_Ok) .. (s_Ok and """" or (""  "" .. tostring(s_Err))))
		if not s_Ok then return end
	else
		s_Node = FindNode(p_Screen, p_Entry.instanceName)
		if s_Node == nil then
			LOG(""  [NODE] "" .. p_Entry.instanceName .. "" NOT found on this screen -- skipped"")
			return
		end
		pcall(function() s_Node:MakeWritable() end)
		if s_Widget ~= nil then
			local s_Ok = pcall(function() s_Node.widgetAsset = UIWidgetAsset(s_Widget) end)
			LOG(""  [NODE] "" .. p_Entry.instanceName .. "" widget -> "" .. tostring(p_Entry.widget) .. "" -> "" .. tostring(s_Ok))
		else
			LOG(""  [NODE] edit "" .. p_Entry.instanceName)
		end
	end
	if s_IsWidget and (#p_Entry.properties > 0 or p_Entry.replaceProperties) then
		WriteProperties(s_Node, p_Entry)
	end
	if s_IsWidget then
		WriteBinding(p_Screen, s_Node, p_Entry)
	end
	WriteFields(s_Node, p_Entry.fields)
	if not p_Entry.new and not s_IsWidget and #(p_Entry.ports or {}) > 0 then
		-- named array ports added to an existing node
		for _, l_Port in ipairs(p_Entry.ports) do
			if ResolvePort(s_Node, l_Port.field .. "":"" .. l_Port.name) == nil then
				pcall(function() s_Node[l_Port.field]:add(NewPort(l_Port.guid, l_Port.name, l_Port.event, l_Port.inputEvent)) end)
			end
		end
	end
	if p_Entry.new then
		local s_Before = #p_Screen.nodes
		local s_Ok, s_Err = pcall(function() p_Screen.nodes:add(s_Node) end)
		LOG(string.format(""    [ADD] nodes:add -> %s (%d -> %d)%s"", tostring(s_Ok), s_Before, #p_Screen.nodes, s_Ok and """" or (""  "" .. tostring(s_Err))))
	end
	Wire(p_Screen, s_Node, p_Entry)
end

-- Shipped wires the document disconnects: each names a UINodeConnection of the screen by its instance guid; the entry is erased
-- from the asset's connection list ('#'/'[i]' 1-based, ':erase' 0-based). Runs before the nodes, so a removed wire can be
-- replaced by a new one between the same ports.
local function Unwire(p_Screen, p_ScreenData)
	for _, r in ipairs(p_ScreenData.removedConnections or {}) do
		local s_Target = Guid(r.guid)
		local s_Index = nil
		for i = 1, #p_Screen.connections do
			local l_Guid = nil
			pcall(function() l_Guid = p_Screen.connections[i].instanceGuid end)
			if l_Guid ~= nil and (l_Guid == s_Target or string.upper(tostring(l_Guid)) == string.upper(r.guid)) then
				s_Index = i
				break
			end
		end
		if s_Index == nil then
			LOG(string.format(""  [UNWIRE] %s -> %s: connection %s not found on this screen -- SKIPPED"", r.from, r.to, r.guid))
		else
			local s_Before = #p_Screen.connections
			local s_Ok, s_Err = pcall(function() p_Screen.connections:erase(s_Index - 1) end)
			LOG(string.format(""  [UNWIRE] %s -> %s -> %s (%d -> %d)%s"", r.from, r.to, tostring(s_Ok), s_Before, #p_Screen.connections, s_Ok and """" or (""  "" .. tostring(s_Err))))
		end
	end
end

local function ApplyScreen(p_ScreenData)
	if p_ScreenData.done then
		return
	end
	local s_Instance = m_Loaded[p_ScreenData.name]
	if s_Instance == nil then
		return
	end
	for l_Name, _ in pairs(p_ScreenData.assets) do
		if m_Loaded[l_Name] == nil then
			return -- a referenced asset (widget, data category, screen...) is still loading; the last handler to fire applies everything
		end
	end
	p_ScreenData.done = true
	-- a screen is a UIScreenAsset; a flow graph (StateNodes/DialogNodes chaining screens) is a plain UIGraphAsset
	local s_Screen = nil
	if p_ScreenData.isScreen ~= false then
		pcall(function() s_Screen = UIScreenAsset(s_Instance) end)
	end
	if s_Screen == nil then
		pcall(function() s_Screen = UIGraphAsset(s_Instance) end)
	end
	if s_Screen == nil then
		LOG(""cast to UIScreenAsset/UIGraphAsset FAILED for "" .. p_ScreenData.name)
		return
	end
	if p_ScreenData.static then
		-- static delivery: the bundle's partition carries every edit; nothing is written here, only what loaded is reported
		-- (a node of ours present = the bundle's copy of the partition is the one the game loaded; a widget node whose
		-- widgetAsset is nil = its import did not resolve when the partition loaded)
		local s_Present = {}
		for _, l_Label in ipairs(p_ScreenData.probe or {}) do
			local l_Node = FindNode(s_Screen, l_Label)
			local l_Asset = ""n/a""
			if l_Node ~= nil then
				pcall(function() l_Asset = tostring(l_Node.widgetAsset ~= nil) end)
			end
			s_Present[#s_Present + 1] = l_Label .. ""="" .. tostring(l_Node ~= nil) .. ""(asset "" .. l_Asset .. "")""
		end
		local s_Imports = {}
		for _, l_Import in ipairs(p_ScreenData.imports or {}) do
			local l_Loaded = false
			pcall(function() l_Loaded = ResourceManager:FindInstanceByGuid(l_Import.partition, l_Import.instance) ~= nil end)
			s_Imports[#s_Imports + 1] = l_Import.name .. ""="" .. tostring(l_Loaded)
		end
		-- every shipped widget node too: which of them lost its asset
		local s_Widgets = {}
		for i = 1, #s_Screen.nodes do
			local l_Node = CastAny(s_Screen.nodes[i])
			if l_Node ~= nil and l_Node.typeInfo.name == ""WidgetNode"" then
				local l_Has = false
				pcall(function() l_Has = l_Node.widgetAsset ~= nil end)
				s_Widgets[#s_Widgets + 1] = NodeLabel(l_Node) .. (l_Has and """" or ""(NO ASSET)"")
			end
		end
		LOG(""[PROBE] "" .. p_ScreenData.name .. "": "" .. #s_Screen.nodes .. "" nodes, "" .. #s_Screen.connections .. "" connections; ours: "" .. (#s_Present > 0 and table.concat(s_Present, "", "") or ""(none)""))
		LOG(""[PROBE] imports loaded: "" .. (#s_Imports > 0 and table.concat(s_Imports, "", "") or ""(none listed)""))
		LOG(""[PROBE] widgets: "" .. table.concat(s_Widgets, "", ""))
		return
	end
	if not pcall(function() s_Screen:MakeWritable() end) then
		LOG(""MakeWritable FAILED for "" .. p_ScreenData.name)
		return
	end
	m_Graph = s_Screen
	LOG(""=== editing "" .. p_ScreenData.name .. "" ("" .. #s_Screen.nodes .. "" nodes, "" .. #s_Screen.connections .. "" connections) ==="")
	if p_ScreenData.fields ~= nil and #p_ScreenData.fields > 0 then
		LOG(""  [SCREEN] fields of the asset"")
		WriteFields(s_Screen, p_ScreenData.fields)
	end
	Unwire(s_Screen, p_ScreenData)
	for _, l_Node in ipairs(p_ScreenData.nodes) do
		ApplyNode(p_ScreenData, s_Screen, l_Node)
	end
	LOG(""=== done: "" .. #s_Screen.nodes .. "" nodes, "" .. #s_Screen.connections .. "" connections ==="")
	m_Graph = nil
end

local function TryApplyAll()
	for _, l_Screen in ipairs(SCREENS) do
		ApplyScreen(l_Screen)
	end
end

for _, l_Screen in ipairs(SCREENS) do
	ResourceManager:RegisterInstanceLoadHandler(l_Screen.partition, l_Screen.instance, function(p_Instance)
		m_Loaded[l_Screen.name] = p_Instance
		-- a screen that (re)loads is the game's own again: edited anew (a screen of a level loads again with every level; a
		-- front-end one loads once and is not edited twice)
		l_Screen.done = false
		TryApplyAll()
	end)
	for l_Name, l_Asset in pairs(l_Screen.assets) do
		ResourceManager:RegisterInstanceLoadHandler(l_Asset.partition, l_Asset.instance, function(p_Instance)
			m_Loaded[l_Name] = p_Instance
			TryApplyAll()
		end)
	end
end

-- The handlers only fire for instances loading AFTER registration; a late mod start would miss them.
Events:Subscribe(""Level:Loaded"", function()
	for _, l_Screen in ipairs(SCREENS) do
		pcall(function()
			m_Loaded[l_Screen.name] = m_Loaded[l_Screen.name] or ResourceManager:FindInstanceByGuid(l_Screen.partition, l_Screen.instance)
			for l_Name, l_Asset in pairs(l_Screen.assets) do
				m_Loaded[l_Name] = m_Loaded[l_Name] or ResourceManager:FindInstanceByGuid(l_Asset.partition, l_Asset.instance)
			end
		end)
	end
	TryApplyAll()
end)

-- ⛔⛔ A LEVEL CHANGE WITH THE CLIENT STILL CONNECTED (2026-09-26, 4 dumps of a client dying at a round change): what m_Loaded
-- holds belongs to the level that ends -- its screens and their assets load again with the next one and their handlers fire
-- again -- so a wrapper kept past the level was dropped only when the next load replaced it, and the collector then finalised
-- it over freed memory (the wrapper's finaliser reads the instance's flags). Every wrapper of the ending level is dropped at its
-- Level:Destroy (what stays loaded -- a front-end screen -- is found again by Level:Loaded above), and a FULL collection runs at
-- the first compartment cleared after it: every Level:Destroy handler of this state has run by then and nothing of the level
-- is freed yet (measured on a bench server: each ResourceManager:ClearCompartment comes BEFORE its compartment is cleared, the
-- mode's before the game's).
local m_LevelGone = false

Events:Subscribe(""Level:Destroy"", function()
	m_Loaded = {}
	m_Graph = nil
	m_LevelGone = true
end)

Events:Subscribe(""ResourceManager:ClearCompartment"", function(p_Compartment)
	if not m_LevelGone then
		return
	end
	m_LevelGone = false
	collectgarbage(""collect"")
end)
";

        /// <summary>
        /// ext/Client tail a document asks for with "as2Channel": the receiver of the ActionScript → Lua channel. Any ActionScript the
        /// document ships can call _global.fbLog(text) (CamoCommon.as defines the sender when no other movie did): the text travels
        /// as bits over requestTypingInput(bool) — the call the vanilla chat box makes — which lands in the client hook
        /// UI:EnableTypingMode; the frame (0x55 sync | len | bytes | xor, MSB first, a closing false) is decoded here, swallowed
        /// (hook:Return(), the engine never sees it) and handed to every mod as the event AS2:Frame(text), printed as [AS2] text.
        /// A real chat toggle is an isolated call and is passed on. The same decoder the AS2LogChannel tool and the recorder's
        /// receiver carry (when the document records, the recorder's receiver decodes and dispatches instead).
        /// </summary>
        public const string As2Channel = @"
-- ---- the ActionScript -> Lua channel (bits over UI:EnableTypingMode; every decoded frame is the event AS2:Frame) ----
local as2_SYNC = 0x55
local as2_BURST_GAP_MS = 60
local as2_STALE_MS = 500
local as2_Bits = {}
local as2_LastMs = 0
local as2_Passthrough = false
local as2_JustCompleted = false
local as2_Stats = { calls = 0, frames = 0, bad = 0, passed = 0, dropped = 0 }

local function as2_BitsToBytes(p_Bits)
	local s_Bytes = {}
	for i = 1, #p_Bits - 7, 8 do
		local l_Value = 0
		for k = 0, 7 do
			l_Value = l_Value * 2 + p_Bits[i + k]
		end
		s_Bytes[#s_Bytes + 1] = l_Value
	end
	return s_Bytes
end

local function as2_Hex(p_Bytes)
	local s_Out = {}
	for _, l_Byte in ipairs(p_Bytes) do
		s_Out[#s_Out + 1] = string.format('%02X', l_Byte)
	end
	return table.concat(s_Out, ' ')
end

local function as2_ExpectedBits(p_Bits)
	if #p_Bits < 16 then
		return nil
	end
	local s_Len = 0
	for k = 9, 16 do
		s_Len = s_Len * 2 + p_Bits[k]
	end
	return 8 * (3 + s_Len)
end

local function as2_Xor8(a, b)
	local s_Result = 0
	local s_Mask = 1
	for _ = 1, 8 do
		local l_A = a % 2
		local l_B = b % 2
		if l_A ~= l_B then
			s_Result = s_Result + s_Mask
		end
		a = (a - l_A) / 2
		b = (b - l_B) / 2
		s_Mask = s_Mask * 2
	end
	return s_Result
end

local function as2_DecodeFrame(p_Bits)
	local s_Bytes = as2_BitsToBytes(p_Bits)
	if #s_Bytes < 3 or s_Bytes[1] ~= as2_SYNC then
		return nil, 'sync', s_Bytes
	end
	local s_Len = s_Bytes[2]
	if #s_Bytes ~= s_Len + 3 then
		return nil, 'length', s_Bytes
	end
	local s_Xor = s_Len
	local s_Chars = {}
	for i = 1, s_Len do
		local l_Byte = s_Bytes[2 + i]
		s_Xor = as2_Xor8(s_Xor, l_Byte)
		s_Chars[#s_Chars + 1] = string.char(l_Byte)
	end
	if s_Xor ~= s_Bytes[#s_Bytes] then
		return nil, string.format('checksum (got %02X want %02X)', s_Bytes[#s_Bytes], s_Xor), s_Bytes
	end
	return table.concat(s_Chars), nil, s_Bytes
end

local function as2_Reset()
	as2_Bits = {}
	as2_Passthrough = false
end

-- a burst that stopped half-way, or an isolated real call (the chat): forgotten, counted
local function as2_Flush(p_Why)
	if #as2_Bits == 0 then
		return
	end
	if #as2_Bits > 1 and not as2_Passthrough then
		as2_Stats.dropped = as2_Stats.dropped + 1
		print(string.format('[AS2CHAN] PARTIAL frame dropped after %d bits (%s)', #as2_Bits, p_Why))
	end
	as2_Reset()
end

Hooks:Install('UI:EnableTypingMode', 1, function(p_Hook, p_Enable)
	as2_Stats.calls = as2_Stats.calls + 1
	local s_Now = SharedUtils:GetTimeMS()
	-- the closing false the sender appends after every frame: swallowed, it belongs to the frame
	if as2_JustCompleted then
		as2_JustCompleted = false
		if #as2_Bits == 0 and (s_Now - as2_LastMs) <= as2_BURST_GAP_MS and not p_Enable then
			as2_LastMs = s_Now
			p_Hook:Return()
			return
		end
	end
	if #as2_Bits > 0 and (s_Now - as2_LastMs) > as2_BURST_GAP_MS then
		as2_Flush('gap ' .. tostring(s_Now - as2_LastMs) .. ' ms')
	end
	as2_LastMs = s_Now
	as2_Bits[#as2_Bits + 1] = p_Enable and 1 or 0
	-- the first call of a burst: unknown yet, passed (a frame starts with false, harmless)
	if #as2_Bits == 1 then
		as2_Stats.passed = as2_Stats.passed + 1
		p_Hook:Pass(p_Enable)
		return
	end
	-- does the burst still look like the sync byte 0x55 = 01010101 ?
	if not as2_Passthrough and #as2_Bits <= 8 then
		local s_Want = (#as2_Bits % 2 == 0) and 1 or 0
		if as2_Bits[#as2_Bits] ~= s_Want then
			as2_Passthrough = true
		end
	end
	if as2_Passthrough then
		as2_Stats.passed = as2_Stats.passed + 1
		p_Hook:Pass(p_Enable)
		return
	end
	-- ours: the engine must not see it
	p_Hook:Return()
	local s_Expected = as2_ExpectedBits(as2_Bits)
	if s_Expected ~= nil and #as2_Bits >= s_Expected then
		local s_Text, s_Error, s_Bytes = as2_DecodeFrame(as2_Bits)
		if s_Text ~= nil then
			as2_Stats.frames = as2_Stats.frames + 1
			print('[AS2] ' .. s_Text)
			Events:Dispatch('AS2:Frame', s_Text)
		else
			as2_Stats.bad = as2_Stats.bad + 1
			print(string.format('[AS2CHAN] frame BAD (%s) raw=%s', tostring(s_Error), as2_Hex(s_Bytes)))
		end
		as2_Reset()
		as2_JustCompleted = true
	end
end)

Events:Subscribe('Engine:Update', function()
	if #as2_Bits > 0 and (SharedUtils:GetTimeMS() - as2_LastMs) > as2_STALE_MS then
		as2_Flush('stale')
	end
end)

Console:Register('as2chan', 'the ActionScript -> Lua channel: stats', function()
	return string.format('calls=%d frames=%d bad=%d passed=%d dropped=%d pending=%d',
		as2_Stats.calls, as2_Stats.frames, as2_Stats.bad, as2_Stats.passed, as2_Stats.dropped, #as2_Bits)
end)
";
    }
}
