<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
    <OutputPath>$(SolutionDir)\bin\$(Configuration)</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <Platforms>AnyCPU</Platforms>
    <Configurations>Release;Debug</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Contexts\GameContext.cs~RF197c0191.TMP" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RimeLib.Content\RimeLib.Content.csproj" />
    <ProjectReference Include="..\RimeLib.Content.Frostbite2_0\RimeLib.Content.Frostbite2_0.csproj" />
	<ProjectReference Include="..\RimeLib.Havok\RimeLib.Havok.csproj" />
	<ProjectReference Include="..\RimeLib.Mesh\RimeLib.Mesh.csproj" />
    <ProjectReference Include="..\RimeLib.Serialization\RimeLib.Serialization.csproj" />
    <ProjectReference Include="..\RimeLib.Shader\RimeLib.Shader.csproj" />
    <ProjectReference Include="..\RimeLib.Terrain\RimeLib.Terrain.csproj" />
    <ProjectReference Include="..\RimeLib.Terrain.Frostbite2_0\RimeLib.Terrain.Frostbite2_0.csproj" />
    <ProjectReference Include="..\RimeLib.Texture\RimeLib.Texture.csproj" />
    <ProjectReference Include="..\RimeLib.Toolkit\RimeLib.Toolkit.csproj" />
    <ProjectReference Include="..\RimeLibLite\RimeLibLite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SharpGLTF.Core">
      <HintPath>..\..\..\.nuget\packages\sharpgltf.core\1.0.5\lib\net8.0\SharpGLTF.Core.dll</HintPath>
    </Reference>
    <Reference Include="SharpGLTF.Toolkit">
      <HintPath>..\..\..\.nuget\packages\sharpgltf.toolkit\1.0.5\lib\net8.0\SharpGLTF.Toolkit.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
